services:
  bot:
    image: halloweex/keycrm-bot:latest
    container_name: keycrm-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  web:
    image: halloweex/keycrm-web:latest
    container_name: keycrm-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
